# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub metrics as SVG image
      uses: lowlighter/metrics@latest
      with:
        token: METRICS_TOKEN
        plugins_errors_fatal: yes
        dryrun: yes
        use_mocked_data: yes
        verify: yes
